image:
  registry: docker.io
  repository: bitnami/sealed-secrets-controller

createController: true
secretName: custom-values

resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
    cpu: 100m

podSecurityContext:
  enabled: true
  fsGroup: 65534

containerSecurityContext:
  enabled: true
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

updateStatus: true

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true

rbac:
  create: true

metrics:
  serviceMonitor:
    enabled: true
    namespace: kube-system
    interval: 30s

  dashboards:
    create: false

extra_config:
  enabled: true