apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-proportional-autoscaler
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - clusters: {}
        - git:
            repoURL: https://github.com/mogopz/argocd-infra
            revision: HEAD
            files:
            - path: config/{{name}}/cluster-proportional-autoscaler.yaml
  template:
    metadata:
      name: cluster-proportional-autoscaler
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://kubernetes-sigs.github.io/cluster-proportional-autoscaler
        targetRevision: 1.1.0
        chart: cluster-proportional-autoscaler
        helm:
          values: |
            nameOverride: coredns-autoscaler

            config:
              linear:
                coresPerReplica: 256
                nodesPerReplica: 16
                min: 5
                max: 100
                preventSinglePointFailure: true
                includeUnschedulableNodes: true

            image:
              repository: registry.k8s.io/cpa/cluster-proportional-autoscaler
              pullPolicy: IfNotPresent

            options:
              namespace: kube-system
              target: {{options.target}}

            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi

            securityContext:
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000

            serviceAccount:
              create: true
              name: coredns-autoscaler
      destination:
        server: "{{server}}"
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - FailOnSharedResource=true