apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: karpenter
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - clusters: {}
        - git:
            repoURL: https://github.com/mogopz/argocd-infra
            revision: HEAD
            files:
            - path: config/{{name}}/karpenter.yaml
  template:
    metadata:
      name: karpenter
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/mogopz/argocd-infra
        targetRevision: HEAD
        path: charts/karpenter
        helm:
          skipCrds: true
          values: |
            imagePullPolicy: IfNotPresent

            serviceAccount:
              create: true
              annotations:
                eks.amazonaws.com/role-arn: "some-arn"
                eks.amazonaws.com/sts-regional-endpoints: "true"

            serviceMonitor:
              enabled: true

            podDisruptionBudget:
              name: karpenter
              maxUnavailable: 1

            podSecurityContext:
              fsGroup: 1000

            priorityClassName: system-cluster-critical

            nodeSelector:
              kubernetes.io/os: linux

            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: topology.kubernetes.io/zone
                whenUnsatisfiable: ScheduleAnyway

            controller:
              resources:
                requests:
                  cpu: 1
                  memory: 1Gi
                limits:
                  memory: 2Gi

            logLevel: info

            settings:
              aws:
                clusterEndpoint: blank
                clusterName: blank
                defaultInstanceProfile: blank
                interruptionQueueName: blank
      destination:
        server: "{{server}}"
        namespace: karpenter
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - FailOnSharedResource=true