apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: sealed-secrets
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/mogopz/argocd-infra
        targetRevision: HEAD
        path: charts/sealed-secrets
        helm:
          valueFiles:
            - "../../config/{{name}}/sealed-secrets.yaml"
      destination:
        server: "{{server}}"
        namespace: sealed-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - FailOnSharedResource=true